spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      ssl.truststore.type: PEM
      ssl.truststore.certificates: ${KAFKA_CA_CERT}
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${PORT:8094}

# Account Service URL for Feign Client
account:
  service:
    url: ${ACCOUNT_SERVICE_URL}

fraud:
  max-transaction-per-minute: 5
  suspicious-amount-multiplier: 5
  max-balance-percentage: 0.90

management:
  endpoints:
    web:
      exposure:
        include: health,info